# Generated by Django 2.2.11 on 2020-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200330_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='max_credit',
            field=models.IntegerField(default=0),
        ),
    ]
