# Generated by Django 2.2.11 on 2020-04-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200401_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_photo',
            field=models.ImageField(default='default.jpg', upload_to='donor_photos'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='credit_till_now',
            field=models.IntegerField(default=0),
        ),
    ]
