# Generated by Django 2.2.11 on 2020-04-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200408_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='business_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='business_photos'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipient_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='recipient_photos'),
        ),
    ]
