# Generated by Django 2.2.11 on 2020-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200409_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='address',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='business_address',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
